name: flake8

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
    flake8-lint:
        runs-on: ubuntu-24.04
        name: Lint
        steps:
            - name: Check out source repository
              uses: actions/checkout@v4
            - name: Set up Python environment
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"
            - name: flake8 Lint
              uses: reviewdog/action-flake8@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  reporter: github-pr-review
